name: serve
on:
  workflow_dispatch:
  push:
    branches:
    - main
permissions: write-all

jobs:
  serve:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
          else
              pip install anyscale==0.5.131 typer==0.9.0 torch transformers scikit-learn ray[default] mlflow fastapi
          fi

      - name: Verify Local Inference Pipeline
        run: |
          mkdir -p mlflow_runs/0/3157b1ab4e9a474bb3539b31d6c48921/artifacts
          PYTHONPATH=. python3 madewithml/predict.py predict \
            --run-id 3157b1ab4e9a474bb3539b31d6c48921 \
            --title "Transfer learning with Transformers" \
            --description "Using BERT for text classification."
